name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build site
      run: |
        # Create build directory
        mkdir -p build
        
        # Copy all files to build directory
        cp -r * build/ 2>/dev/null || true
        
        # Remove the build directory from itself to avoid recursion
        rm -rf build/build 2>/dev/null || true
        
        # Inject API configuration into HTML files
        find build -name "*.html" -type f -exec sed -i 's|<script id="app-config"></script>|<script id="app-config">window.APP_CONFIG = { endpoint: "https://openrouter.ai/api/v1/chat/completions", apiKey: "${{ secrets.OPENROUTER_API_KEY }}", model: "deepseek/deepseek-r1-0528-qwen3-8b:free", additionalHeaders: { "HTTP-Referer": "${{ github.server_url }}/${{ github.repository }}", "X-Title": "AI Personalized Chatbot" } };</script>|g' {} \;

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
